# Generated by Django 4.2.1 on 2023-05-27 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': ''},
        ),
    ]
