# Generated by Django 4.2.1 on 2023-05-27 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson2', '0002_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={},
        ),
    ]
